SELECT [CustomerKey]
      ,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,[FirstName]
      --,[MiddleName]
      ,[LastName]
      ,CONCAT([FirstName] ,' ', [LastName]) as 'FullName'
      --,[NameStyle]
      ,[BirthDate]
      ,[MaritalStatus]
      --,[Suffix]
      ,[Gender]
      --,[EmailAddress]
      ,[YearlyIncome] as 'Income'
      ,[TotalChildren]  
      --,[NumberChildrenAtHome]
      ,[EnglishEducation] as 'Education'
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,[DateFirstPurchase]
      --,[CommuteDistance]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]