SELECT [EmployeeKey]
      --,[ParentEmployeeKey]
      --,[EmployeeNationalIDAlternateKey]
     -- ,[ParentEmployeeNationalIDAlternateKey]
      ,[SalesTerritoryKey]
      ,[FirstName]
      ,[LastName]
     --,[MiddleName]
      ,CONCAT([FirstName], ' ', [LastName]) as 'FullName'
      --,[NameStyle]
      --,[Title]
      --,[HireDate]
      --,[BirthDate]
      --,[LoginID]
      --,[EmailAddress]
      --,[Phone]
      ,[MaritalStatus]
      --,[EmergencyContactName]
      --,[EmergencyContactPhone]
      --,[SalariedFlag]
      ,[Gender]
      --,[PayFrequency]
      --,[BaseRate]
      --,[VacationHours]
      --,[SickLeaveHours]
      --,[CurrentFlag]
      --,[SalesPersonFlag]
      ,[DepartmentName]
      --,[StartDate]
      --,[EndDate]
      --,[Status]
      --,[EmployeePhoto]
  FROM [AdventureWorksDW2019].[dbo].[DimEmployee]